#!/bin/bash


rosrun dynamic_reconfigure dynparam set /cam_forward/realsense2_camera_manager rs435_depth_enable_auto_exposure 0
rosrun dynamic_reconfigure dynparam set /cam_forward/realsense2_camera_manager rs435_depth_exposure 41
rosrun dynamic_reconfigure dynparam set /cam_down/realsense2_camera_manager rs435_depth_enable_auto_exposure 0
rosrun dynamic_reconfigure dynparam set /cam_down/realsense2_camera_manager rs435_depth_exposure 41

rosrun dynamic_reconfigure dynparam set /cam_forward/realsense2_camera_manager rs435_depth_laser_power 0
rosrun dynamic_reconfigure dynparam set /cam_forward/realsense2_camera_manager rs435_depth_emitter_enabled 0
rosrun dynamic_reconfigure dynparam set /cam_down/realsense2_camera_manager rs435_depth_laser_power 0
rosrun dynamic_reconfigure dynparam set /cam_down/realsense2_camera_manager rs435_depth_emitter_enabled 0

# Setup hardware sync
rosrun dynamic_reconfigure dynparam set /cam_forward/realsense2_camera_manager rs435_depth_output_trigger_enabled 0
rosrun dynamic_reconfigure dynparam set /cam_forward/realsense2_camera_manager rs435_depth_frames_queue_size 1
rosrun dynamic_reconfigure dynparam set /cam_down/realsense2_camera_manager rs435_depth_output_trigger_enabled 0
rosrun dynamic_reconfigure dynparam set /cam_down/realsense2_camera_manager rs435_depth_frames_queue_size 1
